version: '3.8'

services:
  mongo:
    image: mongo
    container_name: ping-app-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ping-app-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
